<?php
/**
 * FileApiTest
 * PHP version 5
 *
 * @category Class
 * @package  VentureLeap\StorageService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Storage API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.23
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace VentureLeap\StorageService;

use VentureLeap\StorageService\Configuration;
use VentureLeap\StorageService\ApiException;
use VentureLeap\StorageService\ObjectSerializer;

/**
 * FileApiTest Class Doc Comment
 *
 * @category Class
 * @package  VentureLeap\StorageService
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class FileApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for getFileCollection
     *
     * Retrieves the collection of File resources..
     *
     */
    public function testGetFileCollection()
    {
    }

    /**
     * Test case for getFileItem
     *
     * Retrieves a File resource..
     *
     */
    public function testGetFileItem()
    {
    }

    /**
     * Test case for patchFileItem
     *
     * Updates the File resource..
     *
     */
    public function testPatchFileItem()
    {
    }

    /**
     * Test case for putFileItem
     *
     * Replaces the File resource..
     *
     */
    public function testPutFileItem()
    {
    }
}
